#!/usr/bin/env bash

check_ruby_version () {
  if ! ruby --version | grep `cat .ruby-version`;
  then
    echo "Requested ruby version not active. Please check your setup"
    exit 1
  fi
}

check_bundler () {
  (bundle -v &>/dev/null) || {
    gem install bundler
  }
}

try_ruby_rbenv () {
  if which rbenv &>/dev/null;
  then
    echo "Checking ruby with rbenv"
    rbenv install -s
  else
    echo "rbenv not found. Install with 'brew rbenv', or use something else manually."
  fi
}


try_ruby_rbenv
check_ruby_version
check_bundler
