#!/usr/bin/env bash

check_node_version () {
  if ! node --version | grep `cat .nvmrc`;
  then
    echo "Requested node version not active. Please check your setup"
    exit 1
  fi
}

try_node_nvm () {
  if which nvm &>/dev/null;
  then
    echo "Checking node with nvm"
    nvm install -s
  else
    echo "nvm not found. Install with 'brew nvm', or use something else manually."
  fi
}


try_node_nvm
check_node_version