#!/usr/bin/env bash
if ! (security find-generic-password -s "$1/config/credentials.yml" &> /dev/null);
then
  echo "**********************************************************************"
  echo "* Missing secret key for $1"
  echo "* Copy the secret key from 1password into the clipboard and hit <return>"
  read -e
  security add-generic-password -a "$1-rails-secret" -s "$1/config/credentials.yml" -w "`pbpaste`"
fi
