#!/usr/bin/env bash

check_continue () {
  read -n1 -p "Continue (y/N)? " cont
  if  [ "$cont" != 'y' ];
  then
    echo "ABORT"
    exit 1
  fi
  echo
}

if [[ ! `bundle config $1` == *"$2"* ]]
then
  echo "Setting up bundler config for $1 with options $2"
  check_continue
  bundle config $1 $2
fi
