#!/usr/bin/env bash

install_homebrew_bundle () {
  if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
    brew bundle check >/dev/null 2>&1  || {
      echo "Installing Homebrew dependencies…"
      brew bundle
    }
  fi
}

install_homebrew_bundle
